import React, { useState } from 'react';
import { mockAiRecommendation } from '../../data/mockData';
import { 
  Sparkles, 
  ArrowRight, 
  Truck, 
  CheckCircle2, 
  ShieldCheck, 
  ExternalLink,
  Layers,
  Clock,
  Check
} from 'lucide-react';
import { Modal } from '../common/Modal';

interface AiRecommendationCardProps {
  onExecuteDispatch?: (recommendation: typeof mockAiRecommendation) => void;
}

export const AiRecommendationCard: React.FC<AiRecommendationCardProps> = ({ onExecuteDispatch }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDispatched, setIsDispatched] = useState(false);

  const handleDispatch = () => {
    setIsDispatched(true);
    if (onExecuteDispatch) {
      onExecuteDispatch(mockAiRecommendation);
    }
    setTimeout(() => {
      setIsModalOpen(false);
    }, 1500);
  };

  return (
    <>
      <div className="relative overflow-hidden rounded-xl border-2 border-teal-500 bg-gradient-to-br from-teal-900 via-teal-950 to-slate-950 text-white p-6 shadow-xl">
        {/* Subtle Background Glow */}
        <div className="absolute -right-12 -bottom-12 h-64 w-64 rounded-full bg-teal-500/10 blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-3 flex-1">
            <div className="flex items-center gap-2">
              <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-teal-500 text-slate-950 shadow-sm">
                <Sparkles className="h-3.5 w-3.5 fill-current" />
              </span>
              <span className="text-xs font-bold uppercase tracking-wider text-teal-300">
                AI Autonomous Redistribution Recommendation
              </span>
              <span className="text-[10px] font-bold bg-teal-800/80 text-teal-200 px-2 py-0.5 rounded-full border border-teal-700">
                {mockAiRecommendation.confidenceScore}% Confidence
              </span>
            </div>

            <h3 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
              Transfer 150 units of Paracetamol
            </h3>

            {/* From -> To Route Pill */}
            <div className="flex flex-wrap items-center gap-3 pt-1">
              <div className="rounded-lg bg-white/10 px-3 py-1.5 backdrop-blur-sm border border-white/10 text-xs">
                <span className="text-teal-300 font-semibold">From:</span>{' '}
                <span className="font-bold text-white">PHC-B</span>
              </div>

              <ArrowRight className="h-4 w-4 text-teal-400 shrink-0" />

              <div className="rounded-lg bg-white/10 px-3 py-1.5 backdrop-blur-sm border border-white/10 text-xs">
                <span className="text-teal-300 font-semibold">To:</span>{' '}
                <span className="font-bold text-white">Guna PHC-04</span>
              </div>
            </div>

            {/* Reason */}
            <p className="text-xs text-slate-300 leading-relaxed max-w-2xl pt-1">
              <strong className="text-teal-200">Reason:</strong> Predicted demand exceeds available inventory (viral fever influx detected in Guna district).
            </p>
          </div>

          {/* Action Trigger Button */}
          <div className="shrink-0 flex flex-col sm:flex-row md:flex-col gap-2.5 justify-center">
            <button
              onClick={() => setIsModalOpen(true)}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-teal-400 to-cyan-400 px-5 py-3 text-xs font-extrabold text-slate-950 hover:from-teal-300 hover:to-cyan-300 transition shadow-lg hover:scale-102"
            >
              <Truck className="h-4 w-4" />
              View Recommendation
            </button>
            <span className="text-[11px] text-teal-300/80 text-center font-medium">
              ETA: ~1h 45m via NH-46
            </span>
          </div>
        </div>
      </div>

      {/* Detailed Recommendation Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="AI Redistribution Recommendation Analysis"
        subtitle="Autonomous load balancing recommendation generated by Neural Engine v4.2"
        maxWidth="lg"
      >
        <div className="space-y-4 text-sm">
          {isDispatched ? (
            <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-6 text-center space-y-2">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-600">
                <Check className="h-6 w-6" />
              </div>
              <h4 className="font-bold text-emerald-900 text-base">Redistribution Dispatched Successfully!</h4>
              <p className="text-xs text-emerald-700">
                Dispatched 150 units of Paracetamol from PHC-B to Guna PHC-04. Dispatch Code: <strong>MED-TR-7721</strong>.
              </p>
            </div>
          ) : (
            <>
              <div className="rounded-xl bg-slate-50 p-4 border border-slate-200 space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500">Resource Requested:</span>
                  <span className="font-bold text-slate-900">{mockAiRecommendation.item}</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500">Recommended Quantity:</span>
                  <span className="font-bold text-slate-900">150 Units (1,500 Tablets)</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500">Source Depot:</span>
                  <span className="font-bold text-teal-700">PHC-B (Central Medical Store Depot)</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-500">Receiving Center:</span>
                  <span className="font-bold text-rose-700">Guna PHC-04</span>
                </div>
              </div>

              <div className="rounded-lg bg-teal-50 p-3 border border-teal-200 text-xs text-teal-900 space-y-1">
                <p className="font-bold flex items-center gap-1.5">
                  <ShieldCheck className="h-4 w-4 text-teal-600" />
                  Clinical & Logistical Rationale:
                </p>
                <p className="text-teal-800 leading-relaxed">
                  {mockAiRecommendation.reason}. Guna PHC-04 stock is projected to reach absolute zero in 3.2 days without intervention. PHC-B holds 1,800 units buffer capacity (well above safety line).
                </p>
              </div>

              <div className="flex items-center justify-between p-3 rounded-lg border border-slate-200 text-xs text-slate-600">
                <span className="flex items-center gap-1.5">
                  <Clock className="h-4 w-4 text-slate-400" />
                  Transit Estimate: <strong>{mockAiRecommendation.transitEta}</strong>
                </span>
                <span className="font-semibold text-emerald-700">Impact: 100% Stockout Averted</span>
              </div>

              <div className="flex justify-end gap-3 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="rounded-lg border border-slate-300 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleDispatch}
                  className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-5 py-2 text-xs font-bold text-white hover:bg-teal-700 shadow-sm transition"
                >
                  <Truck className="h-4 w-4" />
                  Confirm & Dispatch Transfer
                </button>
              </div>
            </>
          )}
        </div>
      </Modal>
    </>
  );
};
